services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_DB: smartcontrol
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_container
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:

